[package]
edition = "2021"
name = "elysium-sdl"
version = "0.0.0"

[dependencies.elysium-dl]
path = "../dl"

[dependencies.elysium-mem]
path = "../../mem"

[dependencies.frosting]
git = "https://github.com/elysian6969/frosting.git"
