[package]
name    = "butterscotch"
version = "0.0.1"
edition = "2018"

[dependencies]
anyhow = "1.0"
ctor = "0.1"
libc = "0.2"
libloading = "0.7"
null-terminated = "*"
tracing = "0.1"
tracing-appender = "0.1"
tracing-subscriber = "0.2"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "thin"
