[package]
name    = "butterscotch"
version = "0.0.1"
edition = "2018"

[dependencies.anyhow]
version = "1.0"

[dependencies.ctor]
version = "0.1"

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.7"

[dependencies.parking_lot]
version = "0.11"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-appender]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "thin"
