[package]
name    = "providence"
version = "0.0.1"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies.atomic_float]
path = "crates/atomic_float"

[dependencies.ctor]
version = "0.1"

[dependencies.daisy_chain]
path = "crates/daisy_chain"

[dependencies.findshlibs]
version = "0.10"

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.7"

[dependencies.nalgebra]
version = "0.29"

[dependencies.nalgebra-glm]
version = "0.15"

[dependencies.parking_lot]
version = "0.11"

[dependencies.phf]
features = ["macros"]
version = "0.10"

[dependencies.rand]
version = "0.8"

[dependencies.regex]
version = "1.5"

[dependencies.sdk]
path = "crates/sdk"

[dependencies.spirit]
path = "crates/spirit"

[dependencies.vek]
features = ["repr_simd"]
version = "0.15"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
