[package]
name    = "providence"
version = "0.0.1"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
atomic_float = { path = "crates/atomic_float" }
ctor = "0.1"
daisy_chain = { git = "https://gitdab.com/undefined/daisy_chain.git" }
findshlibs = "0.10"
libc = "0.2"
libloading = "0.7"
parking_lot = "0.11"
rand = "0.8"
regex = "1.5"
sdk = { path = "crates/sdk" }
spirit = { git = "https://gitdab.com/undefined/spirit.git" }
vek = { features = ["repr_simd"], version = "0.15" }
virt = { path = "crates/virt" }
vptr = { path = "crates/vptr" }

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
