[package]
name    = "providence"
version = "0.0.1"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies.atomic_float]
path = "crates/atomic_float"

[dependencies.ctor]
version = "0.1"

[dependencies.daisy_chain]
git = "https://gitdab.com/undefined/daisy_chain"

[dependencies.findshlibs]
version = "0.10"

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.7"

[dependencies.parking_lot]
version = "0.11"

[dependencies.rand]
version = "0.8"

[dependencies.regex]
version = "1.5"

[dependencies.spirit]
git = "https://gitdab.com/undefined/spirit"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-appender]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[dependencies.vek]
features = ["repr_simd"]
version = "0.15"

[dependencies.sdk]
path = "crates/sdk"

[dependencies.vptr]
path = "crates/vptr"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
