[package]
name    = "providence"
version = "0.0.1"
edition = "2021"

[dependencies.ctor]
version = "0.1"

[dependencies.daisy_chain]
git = "https://gitdab.com/undefined/daisy_chain"

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.7"

[dependencies.parking_lot]
version = "0.11"

[dependencies.spirit]
git = "https://gitdab.com/undefined/spirit"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-appender]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[dependencies.vek]
features = ["repr_simd"]
version = "0.15"

[dependencies.vptr]
features = ["libc"]
git = "https://github.com/mov-rax-rax/vptr"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
