[package]
name    = "providence"
version = "0.0.1"
edition = "2021"

[dependencies.ctor]
version = "0.1"

[dependencies.daisy_chain]
git = "https://gitdab.com/undefined/daisy_chain"

[dependencies.libc]
version = "0.2"

[dependencies.libloading]
version = "0.7"

[dependencies.parking_lot]
version = "0.11"

[dependencies.spirit]
git = "https://gitdab.com/undefined/spirit"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-appender]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[dependencies.vek]
features = ["repr_simd"]
version = "0.15"

[dependencies.vptr]
features = ["libc"]
git = "https://gitdab.com/undefined/vptr.git"

# testing

[dependencies.glow]
version = "0.6"

[dependencies.glutin]
path = "../glutin/glutin"

[dependencies.iced_glow]
path = "../iced/glow"

[dependencies.iced_glutin]
path = "../iced/glutin"

[dependencies.iced_winit]
path = "../iced/winit"

[dependencies.raw-window-handle]
version = "0.3"

[dependencies.sdl2]
version = "0.34"

[dependencies.sdl2-sys]
version = "0.34"

[dependencies.winit]
path = "../winit"

# testing

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = "thin"
panic = "abort"
